version: '3.8'

services:
  docusaurus:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Configure the API server URL at build time
        # Override this with your actual API server URL
        REFRAME_API_URL: ${REFRAME_API_URL:-http://localhost:3000}
    ports:
      - "3000:3000"
    environment:
      # Runtime environment variables
      NODE_ENV: production
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
